---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winxp-pvc
spec:
  storageClassName: openebs-usb-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
    